name: Peacock API Test

on:
  workflow_dispatch:   # bisa dijalankan manual dari tab Actions
  push:                # atau otomatis setiap kali ada commit ke repo

jobs:
  run-peacock:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x source/get.sh

      - name: Run Peacock script
        run: ./source/get.sh
